apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-20240308
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: test-20240308
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources:
      - deployments
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test-20240308
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: test-20240308
subjects:
  - kind: ServiceAccount
    name: test-20240308
    namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: dev-sa-test
  namespace: default
spec:
  serviceAccountName: test-20240308
  containers:
    - name: dev-sa-test
      image: stdoutt/dev-sa-test